version: "3.4"
services:

  db:
    image: postgres:12.2
    network_mode: "host"
    environment:
      - POSTGRES_USER=${PGUSER}
      - POSTGRES_PASSWORD=${PGPASSWORD}
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "${DB_DIRNAME}:/var/lib/postgresql/data"

  gateway:
    image: galleri/gateway:${GATEWAY_VSN}
    network_mode: "host"
    environment:
      - GATEWAY_PORT
      - ALLOWED_ORIGIN
      - PUB_PGST_HOST
      - PUB_PGST_PORT
      - SYS_PGST_HOST
      - SYS_PGST_PORT
      - LUA_CODE_CACHE
      - HTTP_ZMQ_HOST
      - HTTP_ZMQ_HTTP_PORT
      - OBJ_BUFFER_SIZE
      - OBJ_STORAGE_HOST
      - OBJ_STORAGE_BUCKET
    volumes:
      - "/etc/localtime:/etc/localtime:ro"

  mg2:
    image: tengelisconsulting/http_zmq:latest
    network_mode: "host"
    environment:
      - PORT=${HTTP_ZMQ_HTTP_PORT}
      - SEND_PORT=${HTTP_ZMQ_WORK_PORT}
      - RECV_PORT=${HTTP_ZMQ_RESP_PORT}
    volumes:
      - "/etc/localtime:/etc/localtime:ro"

  mg2_handler:
    image: galleri/mg2_handler:${MG2_HANDLER_VSN}
    network_mode: "host"
    environment:
      - MG_HOST=${HTTP_ZMQ_HOST}
      - MG_WORK_PORT=${HTTP_ZMQ_WORK_PORT}
      - MG_RESP_PORT=${HTTP_ZMQ_RESP_PORT}
      - SESSION_TIMEOUT_S
      - LOG_LEVEL
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_KEY
    volumes:
      - ${PRIV_KEY_FILE}:/app/priv_key:ro
      - "/etc/localtime:/etc/localtime:ro"

  pub_postgrest:
    image: tengelisconsulting/postgrest:latest
    network_mode: "host"
    environment:
      # postgrest
      - PGST_USER=${PUB_PGST_USER}
      - PGST_PASS=${PUB_PGST_PASS}
      - PGST_PORT=${PUB_PGST_PORT}
      - PGST_SCHEMA=${PUB_PGST_SCHEMA}
      - PGST_ANON_ROLE=${PUB_PGST_ANON_ROLE}
      - PGST_POOL=${PUB_PGST_POOL}
      - PGST_POOL_TIMEOUT=${PUB_PGST_POOL_TIMEOUT}
      # postgres
      - PGHOST
      - PGPORT
      - PGDB
    volumes:
      - "/etc/localtime:/etc/localtime:ro"

  sys_postgrest:
    image: tengelisconsulting/postgrest:latest
    network_mode: "host"
    environment:
      # postgrest
      - PGST_USER=${SYS_PGST_USER}
      - PGST_PASS=${SYS_PGST_PASS}
      - PGST_PORT=${SYS_PGST_PORT}
      - PGST_SCHEMA=${SYS_PGST_SCHEMA}
      - PGST_ANON_ROLE=${SYS_PGST_ANON_ROLE}
      - PGST_POOL=${SYS_PGST_POOL}
      - PGST_POOL_TIMEOUT=${SYS_PGST_POOL_TIMEOUT}
      # postgres
      - PGHOST
      - PGPORT
      - PGDB
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
