#!/bin/bash

DATE_TAG=$(date -u +%Y-%m-%d-%H%M)
GIT_TAG=$(git rev-parse --short --verify HEAD)
TAG=${DATE_TAG}--${GIT_TAG}

do_build() {
    image_name="${1}"
    build_dir="${2}"
    full_image_name=galleri/${image_name}:${TAG}
    docker build -t ${full_image_name} ./${build_dir}
    docker push ${full_image_name}
    docker tag ${full_image_name} galleri/${image_name}:latest
    docker push galleri/${image_name}:latest
}

do_build gateway gateway
do_build auth_worker auth_worker
do_build aws_worker aws_worker
do_build session_worker session_worker

# to make dockerhub happy
docker build -t tengelisconsulting/galleri_backend:latest .
